engines:
  rubocop:
    enabled: true
    exclude_fingerprints:

  bundler-audit:
    enabled: false

  fixme:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - ruby

ratings:
  paths:
  - Gemfile.lock
  - "**.rb"

exclude_paths:
- spec/**/*
- benchmarks/**/*
