engines:
  rubocop:
    enabled: true
    exclude_fingerprints:
    - a6b358051ceb7af2b92a34028cd85b0e

  bundler-audit:
    enabled: false

  fixme:
    enabled: true

  duplication:
    enabled: true
    exclude_fingerprints:
    - d155301f1ed91235c5db306b793cddd6
    - e2ddafaebd868c909253e9231b294e9b

    config:
      languages:
      - ruby

ratings:
  paths:
  - "**.rb"

exclude_paths:
- spec/**/*
- benchmarks/**/*
- .rubocop.yml
