dist: trusty

language: ruby
rvm:
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3"

before_install:
  - gem install bundler

script:
  - bundle exec rspec
  # - bundle exec bin/rubocop

bundler_args: --without development

matrix:
  include:
    - rvm: jruby-20mode # JRuby in 1.9 mode
      dist: precise
